/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto;

import Clases.*;
import javax.swing.JOptionPane;


public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invitado = new javax.swing.JTextField();
        invitado1 = new javax.swing.JTextField();
        invitado2 = new javax.swing.JTextField();
        invitado3 = new javax.swing.JTextField();
        invitado4 = new javax.swing.JTextField();
        invitado5 = new javax.swing.JTextField();
        invitado6 = new javax.swing.JTextField();
        invitado7 = new javax.swing.JTextField();
        invitado8 = new javax.swing.JTextField();
        invitado9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        agregarInv = new javax.swing.JButton();
        numMesa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invitado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitado4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mesa");

        agregarInv.setText("Agregar invitados");
        agregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInvActionPerformed(evt);
            }
        });

        numMesa.setText("1");

        jButton1.setText("Abrir la tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMesa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(agregarInv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(invitado5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invitado4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invitado3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invitado2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invitado1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invitado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(invitado7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(invitado6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(invitado8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(invitado9, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(invitado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invitado9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarInv)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int nMesa=1;
    ListaInvitados listaInvitados=new ListaInvitados();
    private void agregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInvActionPerformed
        try {
            Persona persona =new Persona(invitado .getText(),nMesa);
            Persona persona1=new Persona(invitado1.getText(),nMesa);
            Persona persona2=new Persona(invitado2.getText(),nMesa);
            Persona persona3=new Persona(invitado3.getText(),nMesa);
            Persona persona4=new Persona(invitado4.getText(),nMesa);
            Persona persona5=new Persona(invitado5.getText(),nMesa);
            Persona persona6=new Persona(invitado6.getText(),nMesa);
            Persona persona7=new Persona(invitado7.getText(),nMesa);
            Persona persona8=new Persona(invitado8.getText(),nMesa);
            Persona persona9=new Persona(invitado9.getText(),nMesa);

//si no tiene nada escrito no se agrega a la lista
            if (invitado.getText().equals("")==false){
                ListaPersonas.addPersonas(persona);}



            if (invitado1.getText().equals("")==false){
                ListaPersonas.addPersonas(persona1);}



            if (invitado2.getText().equals("")==false){
                ListaPersonas.addPersonas(persona2);}



            if (invitado3.getText().equals("")==false){
                ListaPersonas.addPersonas(persona3);}



            if (invitado4.getText().equals("")==false){
                ListaPersonas.addPersonas(persona4);}



            if (invitado5.getText().equals("")==false){
                ListaPersonas.addPersonas(persona5);}


            if (invitado6.getText().equals("")==false){
                ListaPersonas.addPersonas(persona6);}



            if (invitado7.getText().equals("")==false){
                ListaPersonas.addPersonas(persona7);}



            if (invitado8.getText().equals("")==false){
                ListaPersonas.addPersonas(persona8);}



            if (invitado9.getText().equals("")==false){
                ListaPersonas.addPersonas(persona9);}
            
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Error: " + ex);
            }
        

        //cada ves que cargue los invitados me va a subir en 1 la mesa en la que estamos

        nMesa=nMesa+1;
        numMesa.setText(Integer.toString(nMesa));
        //limpiamos los lineEdit
        invitado.setText(null);
        invitado1.setText(null);
        invitado2.setText(null);
        invitado3.setText(null);
        invitado4.setText(null);
        invitado5.setText(null);
        invitado6.setText(null);
        invitado7.setText(null);
        invitado8.setText(null);
        invitado9.setText(null);
        

            
       
        
    }//GEN-LAST:event_agregarInvActionPerformed


    private void invitado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitado4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_invitado4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //si ya está abierto no se abre de nuevo
        try {
            if (listaInvitados.isVisible()==false){
                listaInvitados.setVisible(true);
            }

            else{
                 JOptionPane.showMessageDialog(this,"La tabla ya está abierta");
            }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Error: " + ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarInv;
    private javax.swing.JTextField invitado;
    private javax.swing.JTextField invitado1;
    private javax.swing.JTextField invitado2;
    private javax.swing.JTextField invitado3;
    private javax.swing.JTextField invitado4;
    private javax.swing.JTextField invitado5;
    private javax.swing.JTextField invitado6;
    private javax.swing.JTextField invitado7;
    private javax.swing.JTextField invitado8;
    private javax.swing.JTextField invitado9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numMesa;
    // End of variables declaration//GEN-END:variables

}
