/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto;
import Clases.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ListaInvitados extends javax.swing.JFrame {

    
    public ListaInvitados() {
        initComponents();
        cargarTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invMesa = new javax.swing.JTable();
        borrarPersona = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invAlf = new javax.swing.JTable();
        recargarTabla = new javax.swing.JButton();

        invMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Invitados", "Mesa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invMesa);

        borrarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rew-delete-small.gif"))); // NOI18N
        borrarPersona.setText("Borrar");
        borrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(borrarPersona)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarPersona))
        );

        jTabbedPane1.addTab("Lista de invitados por orden de mesa", jPanel1);

        invAlf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Invitados", "Mesa"
            }
        ));
        jScrollPane2.setViewportView(invAlf);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de invitados por orden alfabético", jPanel2);

        recargarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.jpg"))); // NOI18N
        recargarTabla.setText("Actualizar");
        recargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(recargarTabla)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recargarTabla)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarTablaActionPerformed
        // TODO add your handling code here:
        cargarTbl();
    }//GEN-LAST:event_recargarTablaActionPerformed

    private void borrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPersonaActionPerformed
        // TODO add your handling code here:
        borrarPersona();
        

    }//GEN-LAST:event_borrarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaInvitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaInvitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaInvitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaInvitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaInvitados().setVisible(true);
            }
        });
    }
//----------------------------------------------------------------------------------------------------------------------------------
        public void cargarTbl(){
        try {
            //colocamos los invitados en la lista de orden por mesa
            DefaultTableModel modelo = new DefaultTableModel();
            Persona[] lista1 = ListaPersonas.getListaPersonas(); 

            //ArrayList lista2 = ListaPersonasOrdenada.getListaPersonasOrd();
            ArrayList lista2 = new ArrayList<>();
            //le agrego al Arralist vacío que acabo de crear, todas las personas de la lista1
            for (int i=0; i< lista1.length;i++){ 
                lista2.add(new Persona(lista1[i].getNombre(),lista1[i].getNumeroMesa()));
            }
            ListaPersonasOrdenada.ordenarLista(lista2);

            

            modelo.addColumn("");
            modelo.addColumn("Invitados");
            modelo.addColumn("Mesa");        

            for (int i=0; i< lista1.length;i++){
                if(lista1[i] !=null){

                    String[] columna= new String[3];
                    columna[0] = Integer.toString(i+1);//es un contador de invitados
                    columna[1] = lista1[i].getNombre();//colocamos el nombre del invitado
                    columna[2] = Integer.toString(lista1[i].getNumeroMesa());//colocamos el numero de mesa al que corresponde


                    modelo.addRow(columna);


                }

            }




            invMesa.setModel(modelo);
//_________________________________________________________________________________________________________________________________________
       
            //colocamos los invitados en la lista de orden alfabético
            DefaultTableModel modelo2 = new DefaultTableModel();


            
            modelo2.addColumn("");
            modelo2.addColumn("Invitados");
            modelo2.addColumn("Mesa");        
            
            //sabemos que la lista1 tiene la misma cantidad de objetos que lista2

            for (int i=0; i< lista1.length;i++){
                Persona personaAux = (Persona) lista2.get(i);
                if(lista2.get(i) !=null){

                    String[] columna2= new String[3];

                    columna2[0] = Integer.toString(i+1);//es un contador de invitados
                    columna2[1] = personaAux.getNombre();
                    columna2[2] = Integer.toString(personaAux.getNumeroMesa());


                    modelo2.addRow(columna2);

                }
            }
            
            invAlf.setModel (modelo2);
            } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Error: " + ex);
            
            }
                    
                
        }
//------------------------------------------------------------------------------------------------------------        
        public void borrarPersona(){
            try{
                int row = invMesa.getSelectedRow();
                ListaPersonas.borrarPersonas(row);
                cargarTbl();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Error: " + ex);
            }
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPersona;
    private javax.swing.JTable invAlf;
    private javax.swing.JTable invMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton recargarTabla;
    // End of variables declaration//GEN-END:variables
}
